FROM golang:1.22-alpine

WORKDIR /app

COPY . .
COPY cmd/video-hls-service cmd/video-hls-service

RUN apk update && apk add --no-cache ffmpeg

RUN go mod tidy
RUN go build -o app cmd/video-hls-service/main.go

CMD ["./app"]
