FROM golang:1.22-alpine

WORKDIR /app

COPY . .
COPY cmd/upload-mp4-service cmd/upload-mp4-service

RUN apk update && apk add --no-cache ffmpeg

RUN go mod tidy
RUN go build -o app cmd/upload-mp4-service/main.go

CMD ["./app"]
