FROM golang:1.22-alpine

WORKDIR /app

COPY . .
COPY cmd/core-service cmd/core-service

RUN apk update && apk add --no-cache ffmpeg

RUN go mod tidy
RUN go build -o app cmd/core-service/main.go

CMD ["./app"]
