version: "3"

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-ctn
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ndhung
      RABBITMQ_DEFAULT_PASS: duyhung2004
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: h_learning_core
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
