version: '3'

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-ctn
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ndhung
      RABBITMQ_DEFAULT_PASS: duyhung2004