FROM golang:1.22-alpine

WORKDIR /app

COPY . .
COPY cmd/blob-service cmd/blob-service

RUN apk update && apk add --no-cache ffmpeg

RUN go mod tidy
RUN go build -o app cmd/blob-service/main.go

CMD ["./app"]
