core_service:
  host: 0.0.0.0
  port: 10000
  grpc: 9000
  socket: 8000

upload_mp4_service:
  host: 0.0.0.0
  port: 10001
  grpc: 9001
  socket: 8001

encoding_service:
  host: 0.0.0.0
  port: 10002
  grpc: 9002
  socket: 8002

video_hls_service:
  host: 0.0.0.0
  port: 10003
  grpc: 9003
  socket: 8003

blob_service:
  host: 0.0.0.0
  port: 10005
  grpc: 9005
  socket: 8005

public_ip: localhost

psql:
  name: h_learning_core
  port: 5432
  user: postgres
  password: 123456
  host: 13.229.239.235

redis: 13.229.239.235:6379

queue_quantity: queue_mp4_360_p

rabbitmq: amqp://ndhung:duyhung2004@13.229.239.235:5672/

smpt:
  email: abangudot@gmail.com
  host: smtp.gmail.com
  port: 587
  password: jwwtlisxqedfaxce
