version: "3.8"

services:
  core-service:
    image: nguyen040904/core-service:latest
    ports:
      - "10000:10000"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - "/root/data:/app/data"
    restart: always
    stdin_open: true
    tty: true